### ISSUE TITLE
Unexpected results

### ISSUE THREAD

**Issue by iboje** [HalfStackZay/DumpDelegatesandForwardingRules.ps1-Updated-#1]
Hi everyone,

I'm thinking I've got an environment problem, and not an issue with the script, but I thought I'd ask to see if anyone has seen this issue before.

I ran the script, and it gave me output.  However, if I ask a user to check their account, the delegates the script shows don't match the what the user sees.  I added a delegate to my email box, but the script doesn't show the delegate for me.  It's almost as if there is 2 delegate tables - One that the script sees, and one that the users see.  Does this make any sense?

Thanks

**Comment by HalfStackZay** [comment]
Heyo - sorry for the late response. The two things I'd like to think about are: A) Did you reconnect to the EXOP module before re-checking? I don't know whether or not that will affect your results, but That's the first thing I'd try. B) Are the users you're querying actually having delegates set up, and not just a mail forwarding rule? I don't mean to sound rude in any way, shape, or form, I'm just trying to confirm that we're trying to find the same information.

Cheers, buddy!

Let me know what I can do to assist, if you don't have the time this seems like a great issue to dig into.
