### ISSUE TITLE
Get mailbox's UPN in CSV for MailForwardingRulesToExternalDomains.csv

### ISSUE THREAD

**Issue by ByDesign1977** [HalfStackZay/DumpDelegatesandForwardingRules.ps1-Updated-#3]
Hi

Can anyone tell me how to get the mailboxes UPN that has rules to external domains on it as an extra column in the csv that is exported?  At present the details of the rule is exported but no information as to on who's mailox it is setup on?

Many thanks

**Comment by HalfStackZay** [comment]
Again, sorry for the late replies, it's been a whirlwind of a year. My personal process for this has been to simply identify what mailboxes have forwarding rules set up, and then use the security center and o365 admin portal to set up notifications sent directly to the IT department for any mailboxes that have forwarding rules applied, and high alert notifications for forwarding rules set up for external domains. If you're saying that you're not seeing which mailboxes have forwarding (or other rules set up) then that's another issue, and I'd also be happy to help. I schedule monthly audits to address all accounts with mail forwarding rules based off of this report, and of course I address all external mail forwarding requests immediately.

Hope you're well amidst all of this mess. Please let me know if there's anything that I can do to assist with this.
